In [2]:
import numpy as np

In [3]:
x = np.array([1, -1, 1])

a = 3.1

In [4]:
# conmutative property
print(a * x)
print(x * a)

[ 3.1 -3.1  3.1]
[ 3.1 -3.1  3.1]


In [5]:
b = -a

In [6]:
print((b+a)*x)
print(b*x + a*x)

[ 0. -0.  0.]
[0. 0. 0.]


# Soluciones a los ejercicios propuestos
---
**Problema 1.**  
Los vectores unitarios estándar de $\mathbb{R}^4$ son:
- $[1, 0, 0, 0]$
- $[0, 1, 0, 0]$
- $[0, 0, 1, 0]$
- $[0, 0, 0, 1]$
---
**Problema 2.**  
Tres combinaciones lineales de vectores en $\mathbb{R}^3$ para expresar el vector $[1, 1, 1]$ pueden ser:
- $[1, 0, 0] + [0, 1, 0] + [0, 0, 1] = [1, 1, 1]$
- $0.5 \cdot [2, 0, 0] + 0.5 \cdot [0, 2, 0] + [0, 0, 1] = [1, 1, 1]$
- $[0.2, 0.3, 0.5] + [0.8, 0.7, 0.5] = [1, 1, 1]$
---
**Problema 3.**  
Tres combinaciones afines con vectores de $\mathbb{R}^3$ donde $\beta_0 \neq \beta_1 \neq \beta_2$ y $\beta_0 + \beta_1 + \beta_2 = 1$:
- $\beta_0 = 0.2$, $\beta_1 = 0.3$, $\beta_2 = 0.5$
- $\beta_0 = -1$, $\beta_1 = 2$, $\beta_2 = 0$
- $\beta_0 = 1.5$, $\beta_1 = -0.2$, $\beta_2 = -0.3$

In [7]:
# Problema 1: Vectores unitarios estándar de R^4
import numpy as np
unitarios = [np.array([1,0,0,0]), np.array([0,1,0,0]), np.array([0,0,1,0]), np.array([0,0,0,1])]
for i, v in enumerate(unitarios):
    print(f"Vector unitario {i+1}: {v}")

# Problema 2: Combinaciones lineales para [1,1,1]
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])
print("\nCombinación 1:", v1+v2+v3)
print("Combinación 2:", 0.5*np.array([2,0,0]) + 0.5*np.array([0,2,0]) + v3)
print("Combinación 3:", np.array([0.2,0.3,0.5]) + np.array([0.8,0.7,0.5]))

# Problema 3: Combinaciones afines con suma 1 y todos diferentes
betas = [
    [0.2, 0.3, 0.5],
    [-1, 2, 0],
    [1.5, -0.2, -0.3]
]
print("\nCombinaciones afines (suma 1, todos diferentes):")
for i, beta in enumerate(betas):
    print(f"Combinación {i+1}: {beta}, suma = {sum(beta)}")

Vector unitario 1: [1 0 0 0]
Vector unitario 2: [0 1 0 0]
Vector unitario 3: [0 0 1 0]
Vector unitario 4: [0 0 0 1]

Combinación 1: [1 1 1]
Combinación 2: [1. 1. 1.]
Combinación 3: [1. 1. 1.]

Combinaciones afines (suma 1, todos diferentes):
Combinación 1: [0.2, 0.3, 0.5], suma = 1.0
Combinación 2: [-1, 2, 0], suma = 1
Combinación 3: [1.5, -0.2, -0.3], suma = 1.0
