# Suma de Vectores

La suma de vectores es una operación fundamental en álgebra lineal. Consiste en sumar los componentes correspondientes de dos o más vectores para obtener un nuevo vector.

Por ejemplo, si tenemos dos vectores:

$$\vec{a} = [a_1, a_2, a_3]$$
$$\vec{b} = [b_1, b_2, b_3]$$

La suma se define como:

$$\vec{a} + \vec{b} = [a_1 + b_1,\ a_2 + b_2,\ a_3 + b_3]$$

---

## Ejemplo visual

Imagina que los vectores representan colores RGB:

- Rojo: $[255, 0, 0]$
- Verde: $[0, 255, 0]$
- Azul: $[0, 0, 255]$

Sumar estos vectores nos da un nuevo color combinando sus componentes.

---

## Usando numpy

Numpy es una librería de Python que facilita la manipulación y operación de vectores y matrices. Permite realizar la suma de vectores de manera eficiente y sencilla utilizando arreglos (arrays) y operaciones vectorizadas.

---

## Ejercicio

Prueba sumar los siguientes vectores usando la función definida y con numpy:

- $[1, 2, 3, 4, 5]$
- $[-1, -2, -3, -4, 5]$

¿Cuál es el resultado?

## Adicion entre vectores

In [13]:
rojo = [255, 0, 0]
negro = [0, 0, 0]
verde = [0, 255, 0]

In [2]:
# Suma de vectores sin librerias
def suma_vectores(a, b):
    return [i+j for i, j in zip(a,b)]


In [11]:
suma_vectores(rojo, negro)

[255, 0, 0]

In [14]:
suma_vectores(rojo, verde)

[255, 255, 0]

## Usando numpy

In [12]:
import numpy as np

In [15]:
rojo = np.array(rojo)
negro = np.array(negro)
verde = np.array(verde)

In [16]:
rojo + negro

array([255,   0,   0])

In [17]:
rojo + verde

array([255, 255,   0])

In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([-1, -2, -3, -4, 5])

In [22]:
c = a+b

In [23]:
c

array([ 0,  0,  0,  0, 10])

In [24]:
a = np.array([0, 0, 255])
c = rojo + verde + a
c

array([255, 255, 255])